"""delete text fields

Revision ID: 2770451edb03
Revises: a537e470dccd
Create Date: 2025-05-10 12:17:35.879699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2770451edb03"
down_revision: Union[str, None] = "a537e470dccd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        constraint_name="check_text_difficulty_is_positive",
        table_name="learning_texts",
        type_="check",
    )
    op.drop_column("learning_texts", "preview")
    op.drop_column("learning_texts", "difficulty")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_texts",
        sa.Column("difficulty", sa.SMALLINT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "learning_texts",
        sa.Column("preview", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    )
    op.create_check_constraint(
        constraint_name="check_text_difficulty_is_positive",
        table_name="learning_texts",
        condition="difficulty >= 0",
    )
    # ### end Alembic commands ###
