"""new fields and types

Revision ID: 948a4ad5bfe0
Revises: a9e38e578620
Create Date: 2025-03-26 23:21:45.984495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948a4ad5bfe0'
down_revision: Union[str, None] = 'a9e38e578620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_texts', sa.Column('preview', sa.String(length=500), nullable=True))
    op.alter_column('learning_texts', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_texts', 'title',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('learning_texts', 'preview')
    # ### end Alembic commands ###
