"""empty message

Revision ID: a537e470dccd
Revises: eca867bd3506
Create Date: 2025-04-08 14:26:16.162907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a537e470dccd'
down_revision: Union[str, None] = 'eca867bd3506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_texts', 'difficulty',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_texts', 'difficulty',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
