"""type change

Revision ID: eca867bd3506
Revises: 948a4ad5bfe0
Create Date: 2025-03-26 23:38:34.682126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca867bd3506'
down_revision: Union[str, None] = '948a4ad5bfe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_texts', 'difficulty',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_texts', 'difficulty',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
